package gui;

import io.Rle;
import io.UnsupportedRuleException;
import io.Utils;
import io.WorldState;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import world.defined.WarpedWorld;
import world.viewport.AddWorldViewport;

/**
 *
 * @author Ahmed Alshakh <ahmed.s.alshakh@gmail.com>
 */
public class NewGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewGameFrame
     */
    public NewGameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rleFilePathField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chooseRleBtn = new javax.swing.JButton();
        worldDimField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rleFilePathField.setEnabled(false);
        rleFilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rleFilePathFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("from RLE:");

        chooseRleBtn.setText("...");
        chooseRleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRleBtnActionPerformed(evt);
            }
        });

        worldDimField.setText("200");

        jLabel2.setText("World Dimension");

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("New Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(rleFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseRleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(worldDimField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rleFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(chooseRleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(worldDimField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rleFilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rleFilePathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rleFilePathFieldActionPerformed
    private File selectedFile;
    private void chooseRleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRleBtnActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Run Length Encodeing", "rle"));
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }
        selectedFile = fileChooser.getSelectedFile();
        rleFilePathField.setText(selectedFile.getAbsolutePath());
    }//GEN-LAST:event_chooseRleBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        int dim = 0;
        try {
            dim = Integer.parseInt(worldDimField.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cannot read world dim. make sure the field only has an integer", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        WorldState addThis = null;
        if (selectedFile != null) {

            try {
                addThis = new Rle(Utils.readFile(selectedFile)).toWorldState();
            } catch (UnsupportedRuleException ex) {
                JOptionPane.showMessageDialog(this, "The rule in " + selectedFile.getParent() + " is not supported", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (addThis.getDim() > dim) {
                JOptionPane.showMessageDialog(this, "The RLE file has Dim of : " + addThis.getDim() + "The world is smaller than this. Fix this by making the dim bigger or making RLE file smaller", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        MainFrame mf;
        if (addThis == null) {
            mf = new MainFrame(new WarpedWorld(dim));
        } else {
            
            for(int i = 0 ; i< 5 ; i++) {
                System.out.print(i + " ");
                System.out.print(addThis.getRule().newValue(true, i)+"   ");
                System.out.println(addThis.getRule().newValue(false, i)+"   ");
            }
            mf = new MainFrame(new WarpedWorld(dim, addThis.getRule()));
            try {
                mf.startByAdding(addThis);
            } catch (AddWorldViewport.TooBigWorld ex) {
                JOptionPane.showMessageDialog(this, "The world you're trying to add is too large for this game. Please start new game from your Rle file", "Error", JOptionPane.ERROR_MESSAGE);
                mf.dispose();
                return;
            }
        }
        mf.setLocationRelativeTo(this);

        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseRleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField rleFilePathField;
    private javax.swing.JTextField worldDimField;
    // End of variables declaration//GEN-END:variables
}
