package gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Ahmed Alshakh <ahmed.s.alshakh@gmail.com>
 */
public class WorldPane extends javax.swing.JPanel {
	private int width;
	private int height;
	
	public static final Color ALIVE = Color.WHITE;
	public static final Color DEAD = Color.BLACK;
	/**
	 * Creates new form WorldPane
	 * @param width
	 * @param height
	 */
	public WorldPane(int width,int height) {
		this.width = width;
		this.height = height;
		
		//initComponents();
	}
	public WorldPane() {
		this(10,15);
	}
	
	@Override
	public void paintComponent(Graphics g) {
		final int cellSize = 20;
		for(int i = 0 ; i < width ; i++ ) {
			for ( int j = 0 ; j < height ; j++ ) {
				Color st;
				if(Math.random() > 0.5) {
					st = ALIVE;
				} else {
					st = DEAD;
				}
				g.setColor(st);
				g.fillRect(i*cellSize,j*cellSize,cellSize,cellSize);
			}
		}
		g.setColor(Color.GRAY);
		for(int i = 0 ; i <= width ; i++ ) {
			g.drawLine(cellSize*i, 0, cellSize*i, height*cellSize);
			
		}
		for(int i = 0 ; i <= height ; i++ ) {
			g.drawLine(0, cellSize*i,  width*cellSize,cellSize*i);
		}
		
	}
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
